### ISSUE TITLE
Build fails on generateGitRevFile task

### ISSUE THREAD

**Issue by janmotl** [rapidminer/rapidminer-studio#19]
After executing:
```
gradlew jar
```
I get:
```
Execution failed for task ':generateGitRevFile'.
repository not found
```
I tried to initialize the repository with:
```
git init
```
But that just leads to other errors.

How should RapidMiner 7.5.3 be build?

**Comment by JonasWilms** [comment]
I guess you used  **[Download ZIP](https://github.com/rapidminer/rapidminer-studio/archive/master.zip)** instead of 
`git clone https://github.com/rapidminer/rapidminer-studio.git rapidminer-studio-core` 

The build should go through with 
`gradle jar -x generateVersionProperties`

But i'm not sure if this won't cause any issues later.

**Comment by janmotl** [comment]
You are right. I downloaded the files in a zip file. Once I downloaded the files directly with git, the problem disappeared.

However, I identified a new issue with the build script, described in #21.
